# 제품 이상여부 판별 프로젝트


## 1. 데이터 불러오기


### 필수 라이브러리


In [28]:
import os
from pprint import pprint

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)
from sklearn.model_selection import train_test_split
from tqdm import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import VotingClassifier

### 데이터 읽어오기


In [30]:
ROOT_DIR = "data"
RANDOM_STATE = 110

# Load data
train_data = pd.read_csv('C:\\Users\\njh45\\OneDrive\\바탕 화면\\Aimers_Alice_data\\train_data.csv')
train_data

Workorder_Dam  CURE SPEED Collect Result_Dam  \
0        4F1XA938-1                            100   
1        3KPM0016-2                             70   
2        4E1X9167-1                             85   
3        3K1X0057-1                             70   
4        3HPM0007-1                             70   
...             ...                            ...   
40501    3J1XF434-2                             70   
40502    4E1XC796-1                            100   
40503    4C1XD438-1                            100   
40504    3I1XA258-1                             70   
40505    3G1XA501-1                             70   

       HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Dam  \
0                                                  161.4          
1                                                  377.3          
2                                                  551.7          
3                                                 1271.8          
4                                                  377.5          
...                                                  ...          
40501                                              377.3          
40502                                              553.1          
40503                                              161.5          
40504                                             1269.0          
40505                                              377.5          

       HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Dam  \
0                                                  383.1          
1                                                  377.3          
2                                                 1383.9          
3                                                 1271.8          
4                                                  377.5          
...                                                  ...          
40501                                              377.3          
40502                                             1393.5          
40503                                              377.1          
40504                                             1269.0          
40505                                              377.5          

       DISCHARGED SPEED OF RESIN Collect Result_Dam  \
0                                                16   
1                                                10   
2                                                16   
3                                                10   
4                                                10   
...                                             ...   
40501                                            10   
40502                                            16   
40503                                            16   
40504                                            10   
40505                                            10   

       DISCHARGED TIME OF RESIN(Stage1) Collect Result_Dam  \
0                                                   14.9     
1                                                   21.3     
2                                                   14.7     
3                                                   21.3     
4                                                    9.7     
...                                                  ...     
40501                                               17.0     
40502                                               14.9     
40503                                               14.2     
40504                                                9.7     
40505                                                9.6     

       DISCHARGED TIME OF RESIN(Stage2) Collect Result_Dam  \
0                                                    8.4     
1                                                    4.9     
2                                                    8.5     
3                                                    8.4     
4                              

In [31]:
test_data = pd.read_csv('C:\\Users\\njh45\\OneDrive\\바탕 화면\\Aimers_Alice_data\\test_data.csv')
test_data

Workorder_Dam  CURE SPEED Collect Result_Dam  \
0        4F1XA938-1                            100   
1        3KPM0016-2                             70   
2        4E1X9167-1                             85   
3        3K1X0057-1                             70   
4        3HPM0007-1                             70   
...             ...                            ...   
40501    3J1XF434-2                             70   
40502    4E1XC796-1                            100   
40503    4C1XD438-1                            100   
40504    3I1XA258-1                             70   
40505    3G1XA501-1                             70   

       HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Dam  \
0                                                  161.4          
1                                                  377.3          
2                                                  551.7          
3                                                 1271.8          
4                                                  377.5          
...                                                  ...          
40501                                              377.3          
40502                                              553.1          
40503                                              161.5          
40504                                             1269.0          
40505                                              377.5          

       HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Dam  \
0                                                  383.1          
1                                                  377.3          
2                                                 1383.9          
3                                                 1271.8          
4                                                  377.5          
...                                                  ...          
40501                                              377.3          
40502                                             1393.5          
40503                                              377.1          
40504                                             1269.0          
40505                                              377.5          

       DISCHARGED SPEED OF RESIN Collect Result_Dam  \
0                                                16   
1                                                10   
2                                                16   
3                                                10   
4                                                10   
...                                             ...   
40501                                            10   
40502                                            16   
40503                                            16   
40504                                            10   
40505                                            10   

       DISCHARGED TIME OF RESIN(Stage1) Collect Result_Dam  \
0                                                   14.9     
1                                                   21.3     
2                                                   14.7     
3                                                   21.3     
4                                                    9.7     
...                                                  ...     
40501                                               17.0     
40502                                               14.9     
40503                                               14.2     
40504                                                9.7     
40505                                                9.6     

       DISCHARGED TIME OF RESIN(Stage2) Collect Result_Dam  \
0                                                    8.4     
1                                                    4.9     
2                                                    8.5     
3                                                    8.4     
4                              

In [32]:
train_data.columns

Index(['Workorder_Dam', 'CURE SPEED Collect Result_Dam',
       'HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Dam',
       'HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Dam',
       'DISCHARGED SPEED OF RESIN Collect Result_Dam',
       'DISCHARGED TIME OF RESIN(Stage1) Collect Result_Dam',
       'DISCHARGED TIME OF RESIN(Stage2) Collect Result_Dam',
       'Stage1 Line2 Distance Speed Collect Result_Dam',
       'Stage2 Line2 Distance Speed Collect Result_Dam',
       'THICKNESS 2 Collect Result_Dam', 'WorkMode Collect Result_Dam',
       'PalletID Collect Result_Dam', 'Machine Tact time Collect Result_Dam',
       '1st Pressure 1st Pressure Unit Time_AutoClave',
       '1st Pressure Collect Result_AutoClave',
       '2nd Pressure Unit Time_AutoClave',
       '2nd Pressure Collect Result_AutoClave',
       '3rd Pressure Unit Time_AutoClave',
       '3rd Pressure Collect Result_AutoClave',
       'Chamber Temp. Collect Result_AutoClave',
       'DISCHARGED SPEED OF RES

In [33]:
train_data.dtypes

Workorder_Dam                                                  object
CURE SPEED Collect Result_Dam                                   int64
HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Dam      float64
HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Dam      float64
DISCHARGED SPEED OF RESIN Collect Result_Dam                    int64
DISCHARGED TIME OF RESIN(Stage1) Collect Result_Dam           float64
DISCHARGED TIME OF RESIN(Stage2) Collect Result_Dam           float64
Stage1 Line2 Distance Speed Collect Result_Dam                  int64
Stage2 Line2 Distance Speed Collect Result_Dam                  int64
THICKNESS 2 Collect Result_Dam                                float64
WorkMode Collect Result_Dam                                   float64
PalletID Collect Result_Dam                                   float64
Machine Tact time Collect Result_Dam                          float64
1st Pressure 1st Pressure Unit Time_AutoClave                   int64
1st Pressure Collect

In [34]:
train_data.isnull().sum()

Workorder_Dam                                                 0
CURE SPEED Collect Result_Dam                                 0
HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Dam      0
HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Dam      0
DISCHARGED SPEED OF RESIN Collect Result_Dam                  0
DISCHARGED TIME OF RESIN(Stage1) Collect Result_Dam           0
DISCHARGED TIME OF RESIN(Stage2) Collect Result_Dam           0
Stage1 Line2 Distance Speed Collect Result_Dam                0
Stage2 Line2 Distance Speed Collect Result_Dam                0
THICKNESS 2 Collect Result_Dam                                0
WorkMode Collect Result_Dam                                   0
PalletID Collect Result_Dam                                   0
Machine Tact time Collect Result_Dam                          0
1st Pressure 1st Pressure Unit Time_AutoClave                 0
1st Pressure Collect Result_AutoClave                         0
2nd Pressure Unit Time_AutoClave        

In [35]:
from sklearn.preprocessing import LabelEncoder

# LabelEncoder 클래스의 인스턴스를 생성. 이제 해당 클래스의 메서드를 사용할 수 있는 객체가 돼
label_encoder = LabelEncoder()

# 각 df의 데이터들을 학습하고 정수로 매핑함
train_data['Workorder_Dam'] = label_encoder.fit_transform(train_data['Workorder_Dam'])
test_data['Workorder_Dam'] = label_encoder.fit_transform(test_data['Workorder_Dam'])

# train_data에 학습된 매핑을 그대로 적용하기 위해선 아래의 코드를 쓰는게 좋음
# test_data['Workorder_Dam'] = label_encoder.transform(test_data['Workorder_Dam'])

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
train_data['target'] = le.fit_transform(train_data['target'])
train_data

Workorder_Dam  CURE SPEED Collect Result_Dam  \
0                657                            100   
1                283                             70   
2                589                             85   
3                251                             70   
4                142                             70   
...              ...                            ...   
40501            238                             70   
40502            643                            100   
40503            540                            100   
40504            164                             70   
40505             46                             70   

       HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Dam  \
0                                                  161.4          
1                                                  377.3          
2                                                  551.7          
3                                                 1271.8          
4                                                  377.5          
...                                                  ...          
40501                                              377.3          
40502                                              553.1          
40503                                              161.5          
40504                                             1269.0          
40505                                              377.5          

       HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Dam  \
0                                                  383.1          
1                                                  377.3          
2                                                 1383.9          
3                                                 1271.8          
4                                                  377.5          
...                                                  ...          
40501                                              377.3          
40502                                             1393.5          
40503                                              377.1          
40504                                             1269.0          
40505                                              377.5          

       DISCHARGED SPEED OF RESIN Collect Result_Dam  \
0                                                16   
1                                                10   
2                                                16   
3                                                10   
4                                                10   
...                                             ...   
40501                                            10   
40502                                            16   
40503                                            16   
40504                                            10   
40505                                            10   

       DISCHARGED TIME OF RESIN(Stage1) Collect Result_Dam  \
0                                                   14.9     
1                                                   21.3     
2                                                   14.7     
3                                                   21.3     
4                                                    9.7     
...                                                  ...     
40501                                               17.0     
40502                                               14.9     
40503                                               14.2     
40504                                                9.7     
40505                                                9.6     

       DISCHARGED TIME OF RESIN(Stage2) Collect Result_Dam  \
0                                                    8.4     
1                                                    4.9     
2                                                    8.5     
3                                                    8.4     
4                   

target 1 = Normal, 0 = AbNormal

### SMOTE


데이타 불균형을 해결하기 위해 언더 샘플링을 진행합니다.


In [9]:
normal_ratio = 1.0  # 1.0 means 1:1 ratio

df_normal = train_data[train_data["target"] == 1]
df_abnormal = train_data[train_data["target"] == 0]

num_normal = len(df_normal)
num_abnormal = len(df_abnormal)
print(f"Original  Total: Normal: {num_normal}, AbNormal: {num_abnormal}")


Original  Total: Normal: 38156, AbNormal: 2350


In [10]:
# 원본 데이터프레임을 결합
df_combined = pd.concat([df_normal, df_abnormal], axis=0).reset_index(drop=True)

# 특성과 레이블 분리
X = df_combined.drop(columns=["target"])
y = df_combined["target"]

In [11]:
# SMOTE 인스턴스 생성
smote = SMOTE(sampling_strategy='auto', random_state=RANDOM_STATE)

# SMOTE를 사용하여 오버샘플링
X_resampled, y_resampled = smote.fit_resample(X, y)

# 결과 확인
df_resampled = pd.DataFrame(X_resampled, columns=X.columns)
df_resampled["target"] = y_resampled

In [12]:
num_normal_resampled = df_resampled[df_resampled["target"] == 0].shape[0]
num_abnormal_resampled = df_resampled[df_resampled["target"] == 1].shape[0]
print(f"Resampled Total: Normal: {num_normal_resampled}, AbNormal: {num_abnormal_resampled}")


Resampled Total: Normal: 38156, AbNormal: 38156


### 데이터 분할


In [13]:
df_train, df_test = train_test_split(
    df_resampled,
    test_size=0.2,
    stratify=df_resampled["target"],
    random_state=RANDOM_STATE,
)


def print_stats(df: pd.DataFrame):
    num_normal = len(df[df["target"] == 1])
    num_abnormal = len(df[df["target"] == 0])
    print(f"  Total: Normal: {num_normal}, AbNormal: {num_abnormal}" + f" ratio: {num_abnormal/num_normal}")


# Print statistics
print(f"  \tAbnormal\tNormal")
print_stats(df_train)
print_stats(df_test)

  	Abnormal	Normal
  Total: Normal: 30525, AbNormal: 30524 ratio: 0.99996723996724
  Total: Normal: 7631, AbNormal: 7632 ratio: 1.0001310444240596


In [14]:
X_train = df_train.drop(['target'], axis = 1)
y_train = df_train['target']

X_test = df_test.drop(['target'], axis = 1)
y_test = df_test['target']

# 스케일 여부

# 스케일러 X

## 3. 모델 학습


In [15]:
print ("==================================")
print (" ACCURACY OF OTHER ML CLASSIFIERS" )
print ("==================================")

 ACCURACY OF OTHER ML CLASSIFIERS


In [16]:
from sklearn.neighbors import KNeighborsClassifier
print ("\n--- KNN ---")
kn_3 = KNeighborsClassifier(n_neighbors = 3)
kn_3.fit(X_train, y_train)
pred = kn_3.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))

# F1 점수 계산
f1 = f1_score(y_test, pred, pos_label=0)

# F1 점수 출력
print(f"F1 Score: {f1:.4f}")


--- KNN ---
0.8764332044814257
[[7220  412]
 [1474 6157]]
F1 Score: 0.8845


In [17]:
from sklearn.neighbors import KNeighborsClassifier
print ("\n--- KNN ---")
kn_5 = KNeighborsClassifier(n_neighbors = 5)
kn_5.fit(X_train, y_train)
pred = kn_5.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))

# F1 점수 계산
f1 = f1_score(y_test, pred, pos_label=0)

# F1 점수 출력
print(f"F1 Score: {f1:.4f}")


--- KNN ---
0.8504881084976741
[[7175  457]
 [1825 5806]]
F1 Score: 0.8628


In [18]:
from sklearn.neighbors import KNeighborsClassifier
print ("\n--- KNN ---")
kn_7 = KNeighborsClassifier(n_neighbors = 7)
kn_7.fit(X_train, y_train)
pred = kn_7.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))

# F1 점수 계산
f1 = f1_score(y_test, pred, pos_label=0)

# F1 점수 출력
print(f"F1 Score: {f1:.4f}")


--- KNN ---
0.833060342003538
[[7143  489]
 [2059 5572]]
F1 Score: 0.8486


# 4. 제출 데이터(스케일러 X)

In [19]:
test_data

Workorder_Dam  CURE SPEED Collect Result_Dam  \
0                240                             70   
1                509                             70   
2                128                             70   
3                306                             70   
4                415                             70   
...              ...                            ...   
17356            277                             70   
17357            439                             70   
17358            314                             70   
17359              8                             70   
17360            211                             70   

       HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Dam  \
0                                                 1271.3          
1                                                  551.7          
2                                                  377.5          
3                                                  553.6          
4                                                  161.3          
...                                                  ...          
17356                                              552.0          
17357                                              552.0          
17358                                              162.3          
17359                                              377.5          
17360                                              377.3          

       HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Dam  \
0                                                 1271.3          
1                                                 1383.9          
2                                                  377.5          
3                                                 1270.7          
4                                                  377.1          
...                                                  ...          
17356                                             1270.7          
17357                                             1383.9          
17358                                              377.1          
17359                                              377.5          
17360                                              377.3          

       DISCHARGED SPEED OF RESIN Collect Result_Dam  \
0                                                10   
1                                                16   
2                                                10   
3                                                10   
4                                                16   
...                                             ...   
17356                                            10   
17357                                            16   
17358                                            16   
17359                                            10   
17360                                            10   

       DISCHARGED TIME OF RESIN(Stage1) Collect Result_Dam  \
0                                                   17.0     
1                                                   14.2     
2                                                    9.7     
3                                                   21.3     
4                                                   13.2     
...                                                  ...     
17356                                               21.3     
17357                                               13.2     
17358                                               13.2     
17359                                                9.7     
17360                                               17.0     

       DISCHARGED TIME OF RESIN(Stage2) Collect Result_Dam  \
0                                                    4.9     
1                                                    8.3     
2                                                    4.9     
3                                                   10.6     
4                   

## KNN _3

In [20]:
pred_kn_3 = kn_3.predict(test_data)

counter = Counter(pred_kn_3)

print("값 종류별 개수:", counter)

값 종류별 개수: Counter({1: 13932, 0: 3429})


## KNN_5

In [21]:
pred_kn_5 = kn_5.predict(test_data)

counter = Counter(pred_kn_5)

print("값 종류별 개수:", counter)

값 종류별 개수: Counter({1: 13049, 0: 4312})


## KNN_7

In [22]:
pred_kn_7 = kn_7.predict(test_data)

counter = Counter(pred_kn_7)

print("값 종류별 개수:", counter)

값 종류별 개수: Counter({1: 12503, 0: 4858})


## 3가지 모델의 공통 데이터

In [23]:
knn_3_5_7 = np.logical_or(pred_kn_3, pred_kn_5,pred_kn_7).astype(int)

counter = Counter(knn_3_5_7)

print("값 종류별 개수:", counter)

값 종류별 개수: Counter({1: 14187, 0: 3174})


# 스케일러 O

## 모델 학습

In [31]:
print ("==================================")
print (" ACCURACY OF OTHER ML CLASSIFIERS" )
print ("==================================")


 ACCURACY OF OTHER ML CLASSIFIERS


In [24]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(X_train)
train_scaled = ss.transform(X_train)
test_scaled = ss.transform(X_test)

## KNN_3

In [25]:
from sklearn.neighbors import KNeighborsClassifier
print ("\n--- KNN ---")
kn_scaled_3 = KNeighborsClassifier(n_neighbors = 3)
kn_scaled_3.fit(train_scaled, y_train)
pred_scaled_3 = kn_scaled_3.predict(test_scaled)
print(accuracy_score(y_test,pred_scaled_3))
print (confusion_matrix(y_test, pred_scaled_3))

# F1 점수 계산
f1 = f1_score(y_test, pred_scaled_3, pos_label=0)

# F1 점수 출력
print(f"F1 Score: {f1:.4f}")


--- KNN ---
0.9008713883247068
[[7168  464]
 [1049 6582]]
F1 Score: 0.9045


## KNN_5

In [26]:
from sklearn.neighbors import KNeighborsClassifier
print ("\n--- KNN ---")
kn_scaled_5 = KNeighborsClassifier(n_neighbors = 5)
kn_scaled_5.fit(train_scaled, y_train)
pred_scaled_5 = kn_scaled_5.predict(test_scaled)
print(accuracy_score(y_test,pred_scaled_5))
print (confusion_matrix(y_test, pred_scaled_5))

# F1 점수 계산
f1 = f1_score(y_test, pred_scaled_5, pos_label=0)

# F1 점수 출력
print(f"F1 Score: {f1:.4f}")


--- KNN ---
0.8726331651706741
[[7054  578]
 [1366 6265]]
F1 Score: 0.8789


## KNN_7

In [27]:
from sklearn.neighbors import KNeighborsClassifier
print ("\n--- KNN ---")
kn_scaled_7 = KNeighborsClassifier(n_neighbors = 7)
kn_scaled_7.fit(train_scaled, y_train)
pred_scaled_7 = kn_scaled_7.predict(test_scaled)
print(accuracy_score(y_test,pred_scaled_7))
print (confusion_matrix(y_test, pred_scaled_7))

# F1 점수 계산
f1 = f1_score(y_test, pred_scaled_7, pos_label=0)

# F1 점수 출력
print(f"F1 Score: {f1:.4f}")


--- KNN ---
0.8512088056083339
[[6981  651]
 [1620 6011]]
F1 Score: 0.8601


## 4. 제출 데이터 (스케일러 O)


In [28]:
test_data

Workorder_Dam  CURE SPEED Collect Result_Dam  \
0                240                             70   
1                509                             70   
2                128                             70   
3                306                             70   
4                415                             70   
...              ...                            ...   
17356            277                             70   
17357            439                             70   
17358            314                             70   
17359              8                             70   
17360            211                             70   

       HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Dam  \
0                                                 1271.3          
1                                                  551.7          
2                                                  377.5          
3                                                  553.6          
4                                                  161.3          
...                                                  ...          
17356                                              552.0          
17357                                              552.0          
17358                                              162.3          
17359                                              377.5          
17360                                              377.3          

       HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Dam  \
0                                                 1271.3          
1                                                 1383.9          
2                                                  377.5          
3                                                 1270.7          
4                                                  377.1          
...                                                  ...          
17356                                             1270.7          
17357                                             1383.9          
17358                                              377.1          
17359                                              377.5          
17360                                              377.3          

       DISCHARGED SPEED OF RESIN Collect Result_Dam  \
0                                                10   
1                                                16   
2                                                10   
3                                                10   
4                                                16   
...                                             ...   
17356                                            10   
17357                                            16   
17358                                            16   
17359                                            10   
17360                                            10   

       DISCHARGED TIME OF RESIN(Stage1) Collect Result_Dam  \
0                                                   17.0     
1                                                   14.2     
2                                                    9.7     
3                                                   21.3     
4                                                   13.2     
...                                                  ...     
17356                                               21.3     
17357                                               13.2     
17358                                               13.2     
17359                                                9.7     
17360                                               17.0     

       DISCHARGED TIME OF RESIN(Stage2) Collect Result_Dam  \
0                                                    4.9     
1                                                    8.3     
2                                                    4.9     
3                                                   10.6     
4                   

In [29]:
scaled_test = ss.transform(test_data)

## KNN _3

In [30]:
pred_knn_scaled_3 =  kn_scaled_3.predict(scaled_test)

counter = Counter(pred_knn_scaled_3)

print("값 종류별 개수:", counter)

값 종류별 개수: Counter({1: 14717, 0: 2644})


## KNN_5

In [31]:
pred_knn_scaled_5 =  kn_scaled_5.predict(scaled_test)

counter = Counter(pred_knn_scaled_5)

print("값 종류별 개수:", counter)

값 종류별 개수: Counter({1: 14023, 0: 3338})


## KNN_7

In [32]:
pred_knn_scaled_7 =  kn_scaled_7.predict(scaled_test)

counter = Counter(pred_knn_scaled_7)

print("값 종류별 개수:", counter)

값 종류별 개수: Counter({1: 13514, 0: 3847})


# KNN_scaled_5 와 KNN_3 과 공통된 값을 했을 때 0.190 나옴

In [34]:
knn_3and_scaled5 = np.logical_or(pred_knn_scaled_5, pred_kn_3).astype(int)

counter = Counter(knn_3and_scaled5 )

print("값 종류별 개수:", counter)

값 종류별 개수: Counter({1: 15752, 0: 1609})


## 3가지 모델의 공통 데이터

In [35]:
knn_scaled_3_5_7 = np.logical_or(pred_knn_scaled_3, pred_knn_scaled_5,pred_knn_scaled_7).astype(int)

counter = Counter(knn_scaled_3_5_7)

print("값 종류별 개수:", counter)

값 종류별 개수: Counter({1: 14968, 0: 2393})


In [39]:
knn_all = np.logical_or(knn_scaled_3_5_7,knn_3_5_7).astype(int)

counter = Counter(knn_all)

print("값 종류별 개수:", counter)

값 종류별 개수: Counter({1: 16109, 0: 1252})


In [37]:
pred = ["Normal" if x == 1 else "AbNormal" for x in knn_all]

In [38]:

df_sub = pd.read_csv("submission.csv")
df_sub["target"] = pred

# 제출 파일 저장
df_sub.to_csv("submission_knn_all.csv", index=False)

## MINMAX Scaler

In [41]:
print ("==================================")
print (" ACCURACY OF OTHER ML CLASSIFIERS" )
print ("==================================")


 ACCURACY OF OTHER ML CLASSIFIERS


In [42]:
from sklearn.preprocessing import MinMaxScaler
ss = MinMaxScaler()
ss.fit(X_train)
train_scaled = ss.transform(X_train)
test_scaled = ss.transform(X_test)

In [43]:
from sklearn.neighbors import KNeighborsClassifier
print ("\n--- KNN ---")
kn_scaled_3 = KNeighborsClassifier(n_neighbors = 3)
kn_scaled_3.fit(train_scaled, y_train)
pred_scaled_3 = kn_scaled_3.predict(test_scaled)
print(accuracy_score(y_test,pred_scaled_3))
print (confusion_matrix(y_test, pred_scaled_3))

# F1 점수 계산
f1 = f1_score(y_test, pred_scaled_3, pos_label=0)

# F1 점수 출력
print(f"F1 Score: {f1:.4f}")


--- KNN ---
0.9072921444014939
[[7200  432]
 [ 983 6648]]
F1 Score: 0.9105


In [44]:
from sklearn.neighbors import KNeighborsClassifier
print ("\n--- KNN ---")
kn_scaled_5 = KNeighborsClassifier(n_neighbors = 5)
kn_scaled_5.fit(train_scaled, y_train)
pred_scaled_5 = kn_scaled_5.predict(test_scaled)
print(accuracy_score(y_test,pred_scaled_5))
print (confusion_matrix(y_test, pred_scaled_5))

# F1 점수 계산
f1 = f1_score(y_test, pred_scaled_5, pos_label=0)

# F1 점수 출력
print(f"F1 Score: {f1:.4f}")


--- KNN ---
0.8765642403197275
[[7115  517]
 [1367 6264]]
F1 Score: 0.8831


In [45]:
from sklearn.neighbors import KNeighborsClassifier
print ("\n--- KNN ---")
kn_scaled_7 = KNeighborsClassifier(n_neighbors = 7)
kn_scaled_7.fit(train_scaled, y_train)
pred_scaled_7 = kn_scaled_7.predict(test_scaled)
print(accuracy_score(y_test,pred_scaled_7))
print (confusion_matrix(y_test, pred_scaled_7))

# F1 점수 계산
f1 = f1_score(y_test, pred_scaled_7, pos_label=0)

# F1 점수 출력
print(f"F1 Score: {f1:.4f}")


--- KNN ---
0.8519950206381446
[[7048  584]
 [1675 5956]]
F1 Score: 0.8619


## 제출 데이터

In [46]:
test_data

Workorder_Dam  CURE SPEED Collect Result_Dam  \
0                240                             70   
1                509                             70   
2                128                             70   
3                306                             70   
4                415                             70   
...              ...                            ...   
17356            277                             70   
17357            439                             70   
17358            314                             70   
17359              8                             70   
17360            211                             70   

       HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Dam  \
0                                                 1271.3          
1                                                  551.7          
2                                                  377.5          
3                                                  553.6          
4                                                  161.3          
...                                                  ...          
17356                                              552.0          
17357                                              552.0          
17358                                              162.3          
17359                                              377.5          
17360                                              377.3          

       HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Dam  \
0                                                 1271.3          
1                                                 1383.9          
2                                                  377.5          
3                                                 1270.7          
4                                                  377.1          
...                                                  ...          
17356                                             1270.7          
17357                                             1383.9          
17358                                              377.1          
17359                                              377.5          
17360                                              377.3          

       DISCHARGED SPEED OF RESIN Collect Result_Dam  \
0                                                10   
1                                                16   
2                                                10   
3                                                10   
4                                                16   
...                                             ...   
17356                                            10   
17357                                            16   
17358                                            16   
17359                                            10   
17360                                            10   

       DISCHARGED TIME OF RESIN(Stage1) Collect Result_Dam  \
0                                                   17.0     
1                                                   14.2     
2                                                    9.7     
3                                                   21.3     
4                                                   13.2     
...                                                  ...     
17356                                               21.3     
17357                                               13.2     
17358                                               13.2     
17359                                                9.7     
17360                                               17.0     

       DISCHARGED TIME OF RESIN(Stage2) Collect Result_Dam  \
0                                                    4.9     
1                                                    8.3     
2                                                    4.9     
3                                                   10.6     
4                   

In [47]:
scaled_test = ss.transform(test_data)

## KNN_3

In [48]:
pred_knn_scaled_3 =  kn_scaled_3.predict(scaled_test)

counter = Counter(pred_knn_scaled_3)

print("값 종류별 개수:", counter)

값 종류별 개수: Counter({1: 14897, 0: 2464})


## KNN_5

In [49]:
pred_knn_scaled_5 =  kn_scaled_5.predict(scaled_test)

counter = Counter(pred_knn_scaled_5)

print("값 종류별 개수:", counter)

값 종류별 개수: Counter({1: 14048, 0: 3313})


## KNN_7

In [50]:
pred_knn_scaled_7 =  kn_scaled_7.predict(scaled_test)

counter = Counter(pred_knn_scaled_7)

print("값 종류별 개수:", counter)

값 종류별 개수: Counter({1: 13377, 0: 3984})


## 3개 모델 공통 데이터

In [51]:
knn_scaled_3_5_7 = np.logical_or(pred_knn_scaled_3, pred_knn_scaled_5,pred_knn_scaled_7).astype(int)

counter = Counter(knn_scaled_3_5_7)

print("값 종류별 개수:", counter)

값 종류별 개수: Counter({1: 15126, 0: 2235})


# 예측결과 종합하기

# MINMAX and 스케일러 X

In [ ]:
knn_mm_x = np.logical_or(knn_mm_3_5_7,knn_3_5_7).astype(int)

counter = Counter(knn_mm_x)

print("값 종류별 개수:", counter)

## MINMAX and Standard

In [ ]:
knn_mm_ss = np.logical_or(knn_mm_3_5_7,knn_ss_3_5_7).astype(int)

counter = Counter(knn_mm_ss)

print("값 종류별 개수:", counter)

## MINMAX and Standard and 스케일러 X

In [ ]:
knn_mm_ss_x = np.logical_or(knn_mm_x,knn_mm_ss).astype(int)

counter = Counter(knn_mm_ss_x)

print("값 종류별 개수:", counter)

## 4. 제출하기


In [49]:
파일로 만들고 싶은 예측값 = ["Normal" if x == 1 else "AbNormal" for x in 파일로 만들고 싶은 예측값 ]

In [34]:
pred

['Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'AbNormal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'AbNormal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'AbNormal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'AbNormal',
 'Normal',
 'AbNormal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'AbNormal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'AbNormal',
 'Normal',
 'Normal',
 'Normal',
 'AbNormal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'AbNormal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'AbNormal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'AbNormal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',
 'Normal',

In [109]:
df_sub

Set ID  target
0      0001be084fbc4aaa9d921f39e595961b  Normal
1      0005bbd180064abd99e63f9ed3e1ac80  Normal
2      000948934c4140d883d670adcb609584  Normal
3      000a6bfd02874c6296dc7b2e9c5678a7  Normal
4      0018e78ce91343678716e2ea27a51c95  Normal
...                                 ...     ...
17356  ffea508b59934d689b540f95eb3fa730  Normal
17357  ffed8923c8a448a98afc641b770be153  Normal
17358  fff1e73734da40adbe805359b3efb462  Normal
17359  fff8e38bdd09470baf95f71e92075dec  Normal
17360  fffa83e0a13d4c2db4fd8bf905b517d4  Normal

[17361 rows x 2 columns]

In [ ]:
df_sub = pd.read_csv("submission.csv")
df_sub["target"] = pred

# 제출 파일 저장
df_sub.to_csv("submission_knn.csv", index=False)